#include<stdio.h>
int main()
{
    int n,i,at[10],bt[10],pr[10],ct[10],minat,pri,pos,total,count=0,tempat[10],temppr[10];
    printf("Enter the number of processes\n");
    scanf("%d",&n);
    printf("P\tAT\tBT\tPR\n");
    for(i=0;i<n;i++)
    {
        printf("P%d\t",i+1);
        scanf("%d %d %d",&at[i],&bt[i],&pr[i]);
        tempat[i]=at[i];
        temppr[i]=pr[i];
    }
    minat=99;
    for(i=0;i<n;i++)
    {
        if(at[i]<minat)
        minat=at[i];
    }
    total=minat;
    pri=-1;
    pos=-1;
    while(count!=n)
  {
    for(i=0;i<n;i++)
    {
        if(at[i]<=total)
        {
            if(pr[i]>pri)
            {
                pri=pr[i];
                pos=i;
            }
        }
    }
    total+=bt[pos];
    pr[pos]=-1;
    at[pos]=99;
    ct[pos]=total;
    pri=-1;
    count++;
  }
  printf("P\tAT\tBT\tPR\tCT\tWT\tTAT\n");
  for(i=0;i<n;i++)
  {
      printf("P%d\t%d\t%d\t%d\t%d\t%d\t%d\n",i+1,tempat[i],bt[i],temppr[i],ct[i],ct[i]-tempat[i]-bt[i],ct[i]-tempat[i]);
  }
}